config/routes.rb
Rails.application.routes.draw do

  root to: "locations#index"

  resources :locations do
    resources :plates
  end

  get '/plates', to: "plates#list"

  get "/plates_json", to: "plates#plates_json"
  get "/locations_json", to: "locations#locations_json"

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :plates, dependent: :destroy
end

app/models/plate.rb
class Plate < ActiveRecord::Base
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @locations = Location.find(params[:id])
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @locations = Location.new
  end

  def create
    @location = Location.create(location_params)
    redirect_to locations_path(@location)
  end

  def edit
    @location = Location.find(params[:id]) #Why does :id work and :location_id not work?
  end

  def update
    @location = Location.find(params[:id])
    @location.update(location_params)
    redirect_to locations_path(@location)
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path(@location)
  end

  def locations_json
    @location = Location.all
    render status: 200, json: @location.to_json
  end

  private
  def location_params
    params.require(:location).permit(:country, :territory, :territory_type)
  end

end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController

  def index
    @location = Location.find(params[:location_id])
    @plates = @location.plates
  end

  def show
    @plates = Plate.find(params[:id])
  end

  def new
    @location = Location.find(params[:location_id])
    @plate = @location.plates.new
  end

  def create
    # @plate = Plate.new(plate_params)
    # @location = Location.find(params[:location_id])
    # @plate.location_id = @location.id
    # @plate.save

    @location = Location.find(params[:location_id])
    @plate = @location.plates.create!(plate_params)

    redirect_to location_plates_path(@location)
  end

  def edit
    @plate = Plate.find(params[:id])
    @location = Location.find(params[:location_id])
  end

  def update
    @plate = Plate.find(params[:id])
    @plate.update(plate_params)
    redirect_to location_plates_path
  end

  def destroy
    @plate = Plate.find(params[:id])
    @plate.destroy
    redirect_to location_plates_path
  end

  def list
    @plates = Plate.all
  end

  def plates_json
    @plate = Plate.all
    render status: 200, json: @plate.to_json
  end

  private
  def plate_params
    params.require(:plate).permit(:number, :year, :description, :source, :date_acquired)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LicensePlates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <meta charset="utf-8">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">

  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
</head>

<body>

  <div class="jumbotron navbar-fixed-top">
    <div class="container" id="banner">
      <div class="row">
        <div class="col-sm-4 test"><h3 class="stats">Locations (<%= Location.count %>) </h3></div>
        <div class="col-sm-4"><h2 class="title">License Plate Collection</h2></div>
        <div class="col-sm-4"><h3 class="stats">License Plates (<%= Plate.count %>) </h3></div>
      </div>
    </div>
  </div>

  <div class="container links">
    <!-- These need to be links -->
    <div class="col-md-1 text-center" id="route-index-1"><a href="https://github.com/arsm800/license_plates" class="btn btn-primary">See the Code</a></div>
    <div class="col-md-1 text-center" id="route-index-2"> <%= link_to "Locations", locations_path, class: "btn btn-primary" %> </div>
    <div class="col-md-1 text-center" id="route-index-3"> <%= link_to "Plates", plates_path, class: "btn btn-primary" %> </div>
  </div>

  <%= yield %>

</body>
</html>

app/views/locations/edit.html.erb
<h1 class="header"> Update <%= @location.territory %> </h1>

<%= form_for @location do |f| %>
  <%= f.label :country %>
  <%= f.text_field :country %>

  <%= f.label :territory %>
  <%= f.text_field :territory %>

  <%= f.label :territory_type %>
  <%= f.text_field :territory_type %>

  <%= f.submit "Edit" %>

<% end %>

<div class="container">
  <div class="col-md-12">
<%= link_to "Delete", @location, method: :delete, class: "btn btn-primary" %>
  </div>
</div>

app/views/locations/index.html.erb
<div id="bars"></div>

<div class="container add index-top"> <%= link_to "Add Location", new_location_path, class: "btn btn-primary" %> </div>

<div class="container">
  <table class="table table-hover" id="locations">
    <thead>
      <tr>
        <th>Territory</th>
        <th>Country</th>
        <th>Territory Type</th>
        <th>Total</th>
        <th>Edit Location</th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
      <tr>
        <td> <%= link_to location.territory, location_plates_path(location), class: "btn btn-primary"%> </td>
        <td> <%= location.country %> </td>
        <td> <%= location.territory_type %> </td>
        <td> <%= location.plates.count %> </td>
        <td> <%= link_to "Edit", edit_location_path(location), class: "btn btn-primary" %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>

  var barHeight = 500;
  var w = 1500;

  var dataset = [];

  $.getJSON("/plates_json", function(response) {
    dataset = response;
    console.log(dataset);
  });
  //Because the AJAX requests are asynchronous, you must include a callback function and set the response to the variable you hav already defined as an empty array.//

  var xScale = d3.scale.linear()
            .domain([0, d3.max(dataset)])
            .range([0, w])

  var chart = d3.select("#bars")
               .attr("height", barHeight * dataset.length)
               .attr("width", w);

  var bar = chart.selectAll("g")
                 .data(dataset)
                 .enter()
                 .append("g")
                 .attr("transform", function(d, i) {
                   return "translate(0," + i * barHeight + ")";
                 });

  bar.append("rect")
     .attr("width", xScale)
     .attr("height", barHeight - 1);

  bar.append("text")
     .attr("x", function(d) {
       return x(d) - 3;
     })
     .attr("y", barHeight / 2)
     .attr("dy", ".35em")
     .text(function(d) {
       return d;
     })

</script>

app/views/locations/new.html.erb
<h1 class="header">New Location</h1>

<%= form_for @locations do |f| %>
  <%= f.label :country %>
  <%= f.text_field :country %>

  <%= f.label :territory %>
  <%= f.text_field :territory %>

  <%= f.label :territory_type %>
  <%= f.text_field :territory_type %>

  <%= f.submit "Add location" %>

<% end %>

app/views/locations/show.html.erb
<h1 class="header"> Number: <%= @location.country %> </h1>

<h1 class="header"> Year: <%= @location.territory %> </h1>

<h1 class="header"> Territory Type: <%= @location.territory_type %> </h1>

<div> <%= link_to "Plates", location_plates_path(@location) %> </div>

app/views/plates/edit.html.erb
<h1 class="header"> Update <%= @location.territory %> Plate </h1>

<%= form_for [@location, @plate] do |f| %>
  <%= f.label :number %>
  <%= f.text_field :number %>

  <%= f.label :year %>
  <%= f.number_field :year %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :source %>
  <%= f.text_field :source %>

  <%= f.label :date_acquired %>
  <%= f.text_field :date_acquired %>

  <%= f.submit "Edit" %>

<% end %>

<div class="container">
  <div class="col-md-6">
    <%= link_to "Delete", [@location, @plate], method: :delete, class: "btn btn-primary" %>
  </div>
</div>

app/views/plates/index.html.erb
<h1 class="header location"> <%= @location.territory %> (<%= @location.plates.count %>) </h1>

<div class="container"> <%= link_to "Add Plate", new_location_plate_path(@location), class: "btn btn-primary" %> </div>

<div class="container">
  <table class="table table-hover data">
    <thead>
      <tr>
        <th>Update Plate</th>
        <th>Number</th>
        <th>Year</th>
        <th>Description</th>
        <th>Source</th>
        <th>Date Acquired</th>
        <th>Image</th>
      </tr>
    </thead>
    <tbody>
      <% @plates.each do |plate| %>
      <tr>
        <td> <%= link_to "Update", edit_location_plate_path(@location, plate), class: "btn btn-primary" %> </td>
        <td> <%= plate.number %> </td>
        <td> <%= plate.year %> </td>
        <td> <%= plate.description %> </td>
        <td> <%= plate.source %> </td>
        <td> <%= plate.date_acquired %> </td>
        <td> <%= image_tag(plate.image_url, size: "300x180") %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/plates/list.html.erb
<div class="container">
  <table class="table table-hover data" id="plates">
    <thead>
      <tr>
        <th>Number</th>
        <th>Year</th>
        <th>Description</th>
        <th>Source</th>
        <th>Date Acquired</th>
        <th>Image</th>
      </tr>
    </thead>
    <tbody>
      <% @plates.each do |plate| %>
      <tr>
        <td> <%= plate.number %> </td>
        <td> <%= plate.year %> </td>
        <td> <%= plate.description %> </td>
        <td> <%= plate.source %> </td>
        <td> <%= plate.date_acquired %> </td>
        <td> <%= image_tag(plate.image_url, size: "100x60") %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/plates/new.html.erb
<h1 class="header">New <%= @location.territory %> Plate</h1>

<%= form_for [@location, @plate] do |f| %>
  <%= f.label :number %>
  <%= f.text_field :number %>

  <%= f.label :year %>
  <%= f.number_field :year %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :source %>
  <%= f.text_field :source %>

  <%= f.label :date_acquired %>
  <%= f.text_field :date_acquired %>

  <%= f.submit "Add plate!" %>

<% end %>

app/views/plates/show.html.erb
<h1 class="header"> Number: <%= @plates.number %> </h1>

<h1 class="header"> Year: <%= @plates.year %> </h1>

<h1 class="header"> Description: <%= @plates.description %> </h1>

<h1 class="header"> Source: <%= @plates.source %> </h1>

<h1 class="header"> Date Acquired: <%= @plates.date_acquired %> </h1>